//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laundry.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.Payments = new HashSet<Payment>();
        }
    
        public int Order_ID { get; set; }
        public int User_ID { get; set; }
        public int Services_ID { get; set; }
        public int Quantity { get; set; }
        public System.DateTime Date { get; set; }
        public string Order_Status { get; set; }
        public decimal Amount { get; set; }
        public int Laundry_ID { get; set; }
        public int Inventory_ID { get; set; }
    
        public virtual Service Service { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Payment> Payments { get; set; }
        public virtual Inventory Inventory { get; set; }
        public virtual Service Service1 { get; set; }
    }
}
