//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laundry.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Address
    {
        public int User_ID { get; set; }
        public int Order_ID { get; set; }
        public string Address1 { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual User User { get; set; }
    }
}
