//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaundryManagmentSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public int Payment_ID { get; set; }
        public int Order_ID { get; set; }
        public string Payment_Type { get; set; }
        public System.DateTime Payment_Date { get; set; }
    
        public virtual Order Order { get; set; }
    }
}
